// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIOlZ-RCbMh2Wp8Dw7in5QwHyVxfwt5YY',
    appId: '1:740322235590:web:a3afaa9497dfb3fc7af3c7',
    messagingSenderId: '740322235590',
    projectId: 'projectone-45ab5',
    authDomain: 'projectone-45ab5.firebaseapp.com',
    storageBucket: 'projectone-45ab5.firebasestorage.app',
    measurementId: 'G-71C3D8R1YN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBKO7-Rn3Vv4-D0MvZcG7XznpPZEzJ-aE',
    appId: '1:740322235590:android:7215cc28395bcf377af3c7',
    messagingSenderId: '740322235590',
    projectId: 'projectone-45ab5',
    storageBucket: 'projectone-45ab5.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIOlZ-RCbMh2Wp8Dw7in5QwHyVxfwt5YY',
    appId: '1:740322235590:web:a841adf41407d9fd7af3c7',
    messagingSenderId: '740322235590',
    projectId: 'projectone-45ab5',
    authDomain: 'projectone-45ab5.firebaseapp.com',
    storageBucket: 'projectone-45ab5.firebasestorage.app',
    measurementId: 'G-SVT8CCKXHY',
  );
}
